Make style for selection configurable
meggsimum/wegue pull request #176
Opened 2021-02-17 09:33 UTC by JakobMiksch

- Add a property of a default selection style
- It can be overwritten by layer specific selection styles

2021-02-17 13:36 UTC, chrismayer commented
Thanks for this.

Isn't it possible to instantiate the `SelectInteraction` always with 

```js
selectClick = new SelectInteraction({
    layers: [layer],
    style: selectStyle
});
```
and in case `selectStyle` is undefined the default style of the `SelectInteraction` will be applied? So the if/else could be removed?

2021-02-17 15:13 UTC, JakobMiksch commented
@chrismayer true. I removed the if/else  in the latest commit.

2021-02-18 11:38 UTC, chrismayer requested changes

2021-02-18 11:38 UTC, chrismayer commented on app-starter/static/app-conf.json
> +  "defaulSelectStyle": {
```suggestion
  "defaultSelectStyle": {
```

2021-02-18 11:38 UTC, chrismayer commented on docs/wegue-configuration.md
> +| defaulSelectStyle  | The default style for a selected feature | see [style](map-layer-configuration?id=style-for-vectorlayers) |
```suggestion
| defaultSelectStyle  | The default style for a selected feature | see [style](map-layer-configuration?id=style-for-vectorlayers) |
```

2021-02-18 11:38 UTC, chrismayer commented on src/components/ol/Map.vue
> +            selectStyle = OlStyleFactory.getInstance(appConfig.defaulSelectStyle)
```suggestion
            selectStyle = OlStyleFactory.getInstance(appConfig.defaultSelectStyle)
```

2021-02-18 14:17 UTC, JakobMiksch commented
@chrismayer like discussed I removed the `defaultSelectionStyle`

2021-02-18 14:22 UTC, chrismayer approved these changes
LGTM now, thanks!

2021-02-18 14:22 UTC, merged